### PR TITLE
Change `.with_message()` method to take more generic message type

### PR DESCRIPTION
**Pull request by oOBoomberOo**
Implement #156 
This only affect the `.with_message()` method, the underlying data is still String.

### CODE REVIEW

**Comment by jyn514** [comment]
Would it be possible to make the struct generic as well so you don't have to store the full string in memory the whole time? If so I could generate diagnostics at the spot they're issued instead of just before they're displayed. I have several errors that are just a unit variant as a struct but fairly long if you show the error message.

**Comment by oOBoomberOo** [comment]
Look like these are the only place that needs `message` value ([#1](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views.rs#L247), [#2](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views.rs#L247), [#3](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views.rs#L247)) and it shouldn't be much of a trouble to change them.
The only problem would be that you will be exposing more generics which could sometime be annoying to write.

**Comment by brendanzab** [comment]
I guess a tad concerned about the performance implications of this, and how easy it would be to back away from later. Not sure how important it is though. 🤔

**Comment by brendanzab** [comment]
I'm definitely interested in if we can reduce intermediate allocations too. One complicating issue is that it might be important in some places to measure the lengths of messages, or distribute them over lines, or maybe do layout, eg. using the `pretty` crate.

**Comment by brendanzab** [comment]
Sorry, I forgot to comment on the issue when it was made!

Bad maintainer, bad! 😅

**Comment by brendanzab** [comment]
I'm willing to be convinced too. Interested if @Marwes has any thoughts

**Comment by brendanzab** [comment]
(woops, that close was a mistake)

**Comment by oOBoomberOo** [comment]
Maybe we could encourage the use of error enum like in `reusable_diagnostic` example? You can control when to generate the diagnostic (and string).

**Comment by brendanzab** [comment]
I wonder if we could take a `&dyn Display` we'd take a vtable hit, but not a dynamic allocation hit. And taking references would encourage folks not to keep the `Diagnostic` hanging around for long? Just a thought.

**Comment by oOBoomberOo** [comment]
I don't think that will work since that will require the `Display` struct to live until `Diagnostic` is reported.
Considered this example:
```rust
enum Error {
    Foo(PathBuf)
}

impl Error {
    fn report(&self) -> Diagnostic<()> {
        match self {
           Error::Foo(path) => {
               let path = path.display();
               Diagnostic::error().with_message(path)
           }
        }
    }
}
```
`path` is generated locally here and would be immediately drop after that while `Diagnostic` will be use in the outer scope.

**Comment by brendanzab** [comment]
Ahh dang - I guess in that case it would have to be a `Cow`… bleh 🤔

**Comment by jyn514** [comment]
FWIW if the idea is for the diagnostic to be generated as late as possible I don't think we need to generalize this too much, we can just leave it as taking String.

**Comment by brendanzab** [comment]
Gonna close this for now - feel free to make an issue to discuss this further!

**Comment by Johann150** [comment]
I think we should merge this, maybe change from `Display` to `ToString` (anything that implements `Display` already automatically implements `ToString` <https://doc.rust-lang.org/std/string/trait.ToString.html#impl-ToString-4>, but not the other way around).

Deferring the generation of the error message as long as possible is too complex though IMHO.

**Comment by Johann150** [comment]
While we're at it, would it be a good idea to apply the same changes to `Diagnostic::with_code`?

**Pull request merged**
