### PR TITLE
Render overlapping multiline labels properly

### LINKED ISSUE #100: Group labels originating from the same file into a single snippet
As mentioned in #77, Rustc does a clever job of grouping together labels:

It would be super neat if we could do something similar!

At the moment our diagnostics are all spread out:

```
error[E0308]: `case` clauses have incompatible types

   ┌── FizzBuzz.fun:8:12 ───
   │
 8 │     _ _ => num
   │            ^^^ expected `String`, found `Nat`
   │
   = expected type `String`
        found type `Nat`

   ┌── FizzBuzz.fun:4:13 ───
   │
 4 │   fizz₁ num = case (mod num 5) (mod num 3) of
   │ ╭─────────────'
 5 │ │     0 0 => "FizzBuzz"
 6 │ │     0 _ => "Fizz"
 7 │ │     _ 0 => "Buzz"
 8 │ │     _ _ => num
   │ ╰──────────────' `case` clauses have incompatible types
   │

   ┌── FizzBuzz.fun:3:15 ───
   │
 3 │ fizz₁ : Nat → String
   │               ------ expected type `String` found here
   │
```

It would be great if we could collapse things down, for example:

```
error[E0308]: `case` clauses have incompatible types

   ┌── FizzBuzz.fun:8:12 ───
   │
 3 │   fizz₁ : Nat → String
   │                 ------ expected type `String` found here
 4 │   fizz₁ num = case (mod num 5) (mod num 3) of
   │ ╭─────────────'
 5 │ │     0 0 => "FizzBuzz"
 6 │ │     0 _ => "Fizz"
 7 │ │     _ 0 => "Buzz"
 8 │ │     _ _ => num
   │ │            ^^^ expected `String`, found `Nat`
   │ ╰──────────────' `case` clauses have incompatible types
   │
   = expected type `String`
        found type `Nat`
```

Or in the case of that rustc error:

```
error[E0308]: match arms have incompatible types

    ┌─ codespan/src/file.rs:102:34
    :
99  │  ╭──────── match line_index.compare(self.last_line_index()) {
100 │  │             Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
    │  │                               --------------------------------------------- this is found to be of type `std::result::Result<index::ByteIndex, file::LineIndexOutOfBoundsError>`
101 │  │             Ordering::Equal => Ok(self.source_span().end()),
    │  │                                ---------------------------- this is found to be of type `std::result::Result<index::ByteIndex, file::LineIndexOutOfBoundsError>`
102 │  │             Ordering::Greater => LineIndexOutOfBoundsError {
    │ ╭│──────────────────────────────────^
103 │ ││                 given: line_index,
104 │ ││                 max: self.last_line_index(),
105 │ ││             },
    │ ╰│─────────────^ expected enum `std::result::Result`, found struct `file::LineIndexOutOfBoundsError`
106 │  │         }
    │  ╰─────────' `match` arms have incompatible types
    :
    = note: expected type `std::result::Result<index::ByteIndex, file::LineIndexOutOfBoundsError>`
               found type `file::LineIndexOutOfBoundsError`
```

It might be worth studying how [librustc_errors](https://github.com/rust-lang/rust/tree/961a9d6e97a37ff1bb33578721dfa8687054c7b8/src/librustc_errors) does this. There's a bunch of clever logic in [emitter.rs](https://github.com/rust-lang/rust/blob/961a9d6e97a37ff1bb33578721dfa8687054c7b8/src/librustc_errors/emitter.rs) that it might be worth understanding.

### PR DESCRIPTION
**Pull request by brendanzab**
This renders overlapping multiline labels on the same lines of source code. This means that the following example:

```
error[E0308]: match arms have incompatible types

   ┌── codespan/src/file.rs:1:9 ───
   │
 1 │ ╭         match line_index.compare(self.last_line_index()) {
 2 │ │             Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
 3 │ │             Ordering::Equal => Ok(self.source_span().end()),
 4 │ │             Ordering::Greater => LineIndexOutOfBoundsError {
 5 │ │                 given: line_index,
 6 │ │                 max: self.last_line_index(),
 7 │ │             },
 8 │ │         }
   │ ╰─────────' `match` arms have incompatible types
   ·
 2 │               Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
   │                                 --------------------------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 3 │               Ordering::Equal => Ok(self.source_span().end()),
   │                                  ---------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 4 │               Ordering::Greater => LineIndexOutOfBoundsError {
   │ ╭──────────────────────────────────^
 5 │ │                 given: line_index,
 6 │ │                 max: self.last_line_index(),
 7 │ │             },
   │ ╰─────────────^ expected enum `Result`, found struct `LineIndexOutOfBoundsError`
   │
   = expected type `Result<ByteIndex, LineIndexOutOfBoundsError>`
        found type `LineIndexOutOfBoundsError`
```

…is now rendered as:

```
error[E0308]: match arms have incompatible types

   ┌── codespan/src/file.rs:1:9 ───
   │
 1 │   ╭         match line_index.compare(self.last_line_index()) {
 2 │   │             Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
   │   │                               --------------------------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 3 │   │             Ordering::Equal => Ok(self.source_span().end()),
   │   │                                ---------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 4 │   │             Ordering::Greater => LineIndexOutOfBoundsError {
   │ ╭─│──────────────────────────────────^
 5 │ │ │                 given: line_index,
 6 │ │ │                 max: self.last_line_index(),
 7 │ │ │             },
   │ ╰─│─────────────^ expected enum `Result`, found struct `LineIndexOutOfBoundsError`
 8 │   │         }
   │   ╰─────────' `match` arms have incompatible types
   │
   = expected type `Result<ByteIndex, LineIndexOutOfBoundsError>`
        found type `LineIndexOutOfBoundsError`
```

Closes #100

### CODE REVIEW

**Comment by brendanzab** [comment]
Seems to be failing on installing rustfmt 🤔

**Comment by jyn514** [comment]
```
 4 │   │             Ordering::Greater => LineIndexOutOfBoundsError {
   │ ╭─│──────────────────────────────────^
 5 │ │ │
```
This bit looks a little odd, at least with my fonts: the bars aren't straight and instead wiggle out to the side a little. Does it look different on your computer?
image

**Comment by brendanzab** [comment]
Hmmm, this is what it looks like to me:

Screen Shot 2020-03-24 at 11 28 32 pm

Something must be up with the font stack? Blegh :(

**Comment by brendanzab** [comment]
Like, one font in your stack must not have the rounded corners, so it's falling back to another font with different character widths. :[

**Comment by jyn514** [comment]
What font are you using?

**Comment by brendanzab** [comment]
Seems like it's using Menlo on my system:

Screen Shot 2020-03-25 at 6 47 44 am

Perhaps we should make a separate issue regarding the multiline corner characters? We might have to switch them to regular box drawing corners, which would make me very sad, but this keeps popping up, sadly.

Other than that does this look ok to you?

**Comment by brendanzab** [comment]
If you're on Linux, maybe Liberation Mono would be a good choice?

**Comment by jyn514** [comment]
I tried liberation mono but it doesn't have the fonts for the rounded corner so it just falls back to Noto Sans (and I'm not sure what's going on with the `|` out of place). I don't think it should block this but if I've had this much trouble other people are probably having difficulty as well, we should think about something that works in more common fonts.

**Comment by brendanzab** [comment]
Yeah that's mighty frustrating! Gah.

**Comment by brendanzab** [comment]
Ok, I think I'll merge this now!

**Pull request merged**
