### PR TITLE
Support multi-line diagnostics

### PR DESCRIPTION
**Pull request by lpil**
Hi! I needed multi-line diagnostics for [Gleam](https://github.com/lpil/gleam) so I've added support here.

I'm not very experienced with Rust so please let me know if there are any problems with this  Thanks! :)

Closes https://github.com/brendanzab/codespan/issues/23

### CODE REVIEW

**Comment by lpil** [comment]
Here's how it looks for the example

screenshot 2019-02-24 at 20 18 44

**Comment by brendanzab** [comment]
Oooh, so cool!

**Comment by brendanzab** [comment]
Note that this might be hard for non-coloured outputs to understand. In the future we might need some fancier line underlining like rustc does, but so far this is a great start!

**Comment by brendanzab** [comment]
Note that this might be hard for non-coloured outputs to understand. In the future we might need some fancier line underlining like rustc does, but so far this is a great start!

**Comment by lpil** [comment]
Thank you!

**Comment by brendanzab** [comment]
Feel free to say hello in [our Gitter channel](https://gitter.im/codespan-rs/Lobby)! I'll have to get around to publishing this I guess! Also have a look at this issue too: https://github.com/brendanzab/codespan/issues/52 - I've been unsure how best to proceed with it. 😅 

Appreciate your help, thanks!

**Pull request merged**
