### PR TITLE
Add spacing configuration

### PR DESCRIPTION
**Pull request by brendanzab**
This adds three levels of spacing for rich diagnostics:

-   Cosy (default):
    ```
    error: unknown builtin: `NATRAL`

       ┌─ Data/Nat.fun:7:13
       │
     7 │ {-# BUILTIN NATRAL Nat #-}
       │             ^^^^^^ unknown builtin
       │
       = there is a builtin with a similar name: `NATURAL`

    error[E0001]: unexpected type in application of `_+_`

        ┌─ Test.fun:4:11
        │
      4 │ _ = 123 + "hello"
        │           ^^^^^^^ expected `Nat`, found `String`
        │
        ┌─ Data/Nat.fun:11:1
        │
     11 │ _+_ : Nat → Nat → Nat
        │ --------------------- based on the definition of `_+_`
        │
        = expected type `Nat`
             found type `String`

    ```

-   Compact:
    ```
    error: unknown builtin: `NATRAL`
      ┌─ Data/Nat.fun:7:13
      │
    7 │ {-# BUILTIN NATRAL Nat #-}
      │             ^^^^^^ unknown builtin
      │
      = there is a builtin with a similar name: `NATURAL`

    error[E0001]: unexpected type in application of `_+_`
       ┌─ Test.fun:4:11
       │
     4 │ _ = 123 + "hello"
       │           ^^^^^^^ expected `Nat`, found `String`
       │
       ┌─ Data/Nat.fun:11:1
       │
    11 │ _+_ : Nat → Nat → Nat
       │ --------------------- based on the definition of `_+_`
       │
       = expected type `Nat`
            found type `String`
    ```

-   Compressed:
    ```
    error: unknown builtin: `NATRAL`
      ┌─ Data/Nat.fun:7:13
    7 │ {-# BUILTIN NATRAL Nat #-}
      │             ^^^^^^ unknown builtin
      = there is a builtin with a similar name: `NATURAL`
    error[E0001]: unexpected type in application of `_+_`
       ┌─ Test.fun:4:11
     4 │ _ = 123 + "hello"
       │           ^^^^^^^ expected `Nat`, found `String`
       ┌─ Data/Nat.fun:11:1
    11 │ _+_ : Nat → Nat → Nat
       │ --------------------- based on the definition of `_+_`
       = expected type `Nat`
            found type `String`
    ```

### CODE REVIEW

**Comment by brendanzab** [comment]
There's tradeoffs to making this configurable - it could lead to inconsistency, etc. and just pushes off the choice of a default. It's also currently hard to expose a consistent configuration for codespan-reporting between applications that use it. I prefer the 'cosy' setting at the moment, but yeah, feel free to add your thoughts here!

**Comment by jonathandturner** [comment]
+1 for Compact, but I'm biased :)

**Comment by jyn514** [comment]
`Compressed` looks great to me! I'll probably add a newline between errors on my end.

This might be the feature that makes me switch to codespan-reporting :)

**Comment by brendanzab** [comment]
> I'll probably add a newline between errors on my end.

Do you think this should be the default? 🤔

**Comment by jyn514** [comment]
I would be happy either way. I think most people will want a newline in between, but it's also easy enough to do on my side and if you add it in codespan there's no way to opt-out. So, up to you.

**Comment by jonathandturner** [comment]
Compressed with the newline also sounds good to me

**Comment by brendanzab** [comment]
> it's also easy enough to do on my side and if you add it in codespan there's no way to opt-out.

The trouble with that is then you'd have to match on the spacing config yourself in order to handle if the user requested a more relaxed spacing. I guess I'm starting to get a bit scared of fragmentation when it comes to lots of different styles of rendering… hehe 😅

**Comment by jyn514** [comment]
Sure, then keep it at compressed with newline for consistency. That works for me :)

**Comment by brendanzab** [comment]
I guess I'm kind of uncomfortable merging this right before we have a good way of exposing the display configuration in a consistent way between users of `codespan-reporting`. I kind of fear that we'll end up with a bunch of people with different configurations hard-wired into their binaries. How would everyone feel about going with me making a new PR that uses the 'compact' style?

**Comment by jonathandturner** [comment]
@brendanzab - and move to 'compact' as the default?  sure that'd be fine with me

**Comment by jonathandturner** [comment]
@brendanzab - any luck on settling on a design?

**Comment by brendanzab** [comment]
@jonathandturner thanks for the nudge! It's been on my todo list this week, along with publishing a new version 😅 - made a new PR here: #235

**Comment by brendanzab** [comment]
We might want to introduce this configuration later, but for now I'm closing this.

**Pull request closed without merging**
