### PR TITLE
String -> OsString

### PR DESCRIPTION
**Pull request by jyn514**
Allows storing arbitrary filenames in `File`

Closes https://github.com/brendanzab/codespan/issues/150

### CODE REVIEW

**Comment by jyn514** [comment]
Note that you can still pass in a `&str` and compare retrieved `&OsStr` objects to `&str` because of the `Into<>` bound and autodereferencing magic :)

**Comment by jyn514** [comment]
Whoops, I forgot to update `codespan-reporting` too, one sec.

**Comment by brendanzab** [comment]
Looks good! Merging when ready.

**Comment by jyn514** [comment]
This is ready :)

**Pull request merged**
